DELIMITER $$

DROP PROCEDURE IF EXISTS CONCEPTO_PROYECTO_GET$$

CREATE PROCEDURE `CONCEPTO_PROYECTO_GET`(
 IN P_id_proyecto CHAR(10)
)
BEGIN
 SELECT
 C.id_concepto
 FROM CONCEPTOXPROYECTO C
 WHERE C.id_proyecto = P_id_proyecto
 AND flagactivo = 1;
END$$