DELIMITER $$

DROP PROCEDURE IF EXISTS GET_RENDICION$$

CREATE PROCEDURE `GET_RENDICION`(
 IN P_rendicion	VARCHAR(1)
)
BEGIN
	SELECT
		rendicion
	FROM
		NUEVA_TRANSACCION
	WHERE
		rendicion <> ''
	ORDER BY id_transaccion DESC
	LIMIT 1;
END$$