DELIMITER $$

DROP PROCEDURE IF EXISTS GET_ULTIMA_FECHA$$

CREATE PROCEDURE `GET_ULTIMA_FECHA`(
 IN P_rendicion	VARCHAR(1)
)
BEGIN
	SELECT
		fecha_sistema
	FROM
		NUEVA_TRANSACCION
	WHERE eliminada IS NULL
	ORDER BY fecha_sistema DESC
	LIMIT 1;
END$$