delimiter $$

DROP PROCEDURE IF EXISTS MPC_TC_CONFIGURACION_ACCESO_GET2$$

CREATE PROCEDURE `MPC_TC_CONFIGURACION_ACCESO_GET2`( IN P_ConfigId CHAR(96) )
BEGIN SELECT CA.PerfilId, CA.AplicacionId, CA.ClaseId, CA.FuncionId, CA.Codigo, CA.FlagActivo FROM MPC_TC_CONFIGURACION_ACCESO CA WHERE P_ConfigId = CONCAT(CA.PerfilId, CA.AplicacionId, CA.ClaseId, CA.FuncionId); END$$
