delimiter $$

DROP PROCEDURE IF EXISTS MPC_TC_CONFIGURACION_ACCESO_GET$$

CREATE PROCEDURE `MPC_TC_CONFIGURACION_ACCESO_GET`( IN P_Perfil VARCHAR(10), IN P_App VARCHAR(32), IN P_Clase VARCHAR(32), IN P_Funcion VARCHAR(32), IN P_Opcion CHAR(1) )
BEGIN CASE P_Opcion WHEN 'M' THEN SELECT CA.FuncionId FROM MPC_TC_CONFIGURACION_ACCESO CA INNER JOIN MPC_TC_OBJETO O ON CA.ClaseId = O.ObjetoId WHERE CA.PerfilId = P_Perfil AND CA.AplicacionId = P_App AND O.ObjetoPadreId = 'menu' AND CA.FlagActivo = 'S' ORDER BY CA.FuncionId ASC; WHEN 'C' THEN SELECT CA.FuncionId FROM MPC_TC_CONFIGURACION_ACCESO CA INNER JOIN MPC_TC_OBJETO O ON CA.ClaseId = O.ObjetoId WHERE CA.PerfilId = P_Perfil AND CA.AplicacionId = P_App AND CA.ClaseId = P_Clase AND CA.FuncionId = P_Funcion AND O.ObjetoPadreId = 'class' AND CA.FlagActivo = 'S'; END CASE; END$$
