DELIMITER $$

DROP PROCEDURE IF EXISTS NUEVA_TRANSACCION_AGRUP_INSERT$$

CREATE PROCEDURE `NUEVA_TRANSACCION_AGRUP_INSERT`( 
 IN P_Tipo_transaccion			VARCHAR(15),
 IN P_rendicion				CHAR(9),
 IN P_fecha_registro			DATETIME,
 IN P_fecha_sistema			DATETIME,
 IN P_documento				VARCHAR(20),
 IN P_tipo_cambio			DECIMAL(10,2),
 IN P_importe				DECIMAL(10,2),
 IN P_importedol			DECIMAL(10,2),
 IN P_id_cajabanco			VARCHAR(10),
 IN P_nro_boucher			VARCHAR(25),
 IN P_id_subcentroasignacion            VARCHAR(10),
 IN P_id_centro_asignacion		VARCHAR(10),
 IN P_id_subconsepto			VARCHAR(10),
 IN P_id_concepto			VARCHAR(10),
 IN P_observacion			VARCHAR(50),
 IN P_id_empresa			VARCHAR(10),
 IN P_glosa				VARCHAR(25),
 IN P_id_cuecontable			VARCHAR(10),
 IN P_id_cuecontablecr			VARCHAR(10),
 IN P_fecha_doc				DATETIME,
 IN P_nro_doc				VARCHAR(25),
 IN P_id_cuecontablecc			VARCHAR(10),
 IN P_id_cuecontablecccr		VARCHAR(10),
 IN P_fecha_doccc			DATETIME,
 IN P_glosacc				VARCHAR(25),
 IN P_num_agr				INT
)
BEGIN 
	INSERT INTO NUEVA_TRANSACCION_AGRUP(
	Tipo_transaccion,
	rendicion,
	fecha_registro,
	fecha_sistema,
	documento,
	tipo_cambio,
	importe,
	importedol,
	id_cajabanco,
	nro_boucher,
	id_subcentroasignacion,
	id_centro_asignacion,
	id_subconsepto,
	id_concepto,
	observacion,
	id_empresa,
	id_cuecontable,
	id_cuecontablecr,
	fecha_doc,
	glosa,
	nro_doc,
	id_cuecontablecc,
	id_cuecontablecccr,
	fecha_doccc,
	glosacc,
	num_agr)
	VALUES(
	P_Tipo_transaccion,
	P_rendicion,
	P_fecha_registro,
	P_fecha_sistema,
	P_documento,
	P_tipo_cambio,
	P_importe,
	P_importedol,
	P_id_cajabanco,
	P_nro_boucher,
	P_id_subcentroasignacion,
	P_id_centro_asignacion,
	P_id_subconsepto,
	P_id_concepto,
	P_observacion,
	P_id_empresa,
	P_id_cuecontable,
	P_id_cuecontablecr,
	P_fecha_doc,
	P_glosa,
	P_nro_doc,
	P_id_cuecontablecc,
	P_id_cuecontablecccr,
	P_fecha_doccc,
	P_glosacc,
	P_num_agr);
END$$