DELIMITER $$

DROP PROCEDURE IF EXISTS TRANSACCION_AGR_INSERT$$

CREATE PROCEDURE `TRANSACCION_AGR_INSERT`(
 IN P_descripcion VARCHAR(200)
)
BEGIN
/*
DECLARE P_ERROR VARCHAR(100);
 DECLARE CONTINUE HANDLER FOR SQLSTATE '23000'
 SELECT P_ERROR;
 IF ((SELECT COUNT(descripcion)
	 FROM TRANSACCION_AGR
	 WHERE BINARY descripcion = P_descripcion)>0)
 THEN SET P_ERROR = 'Ya existe un registro con esa descripción.';
 ELSE*/
	INSERT INTO TRANSACCION_AGR(
	descripcion
	)VALUES(
	P_descripcion
	);
/*
 END IF;
 SELECT P_ERROR AS Mensaje;
*/
END